#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2

proto_library(
  name = "common_protocol_proto_lib",
  srcs = ["Common.proto"],
)
